# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterfaceFIR.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(978, 763)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("background-color: #22222e")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(580, 520, 101, 51))
        self.pushButton.setMouseTracking(False)
        self.pushButton.setTabletTracking(False)
        self.pushButton.setStyleSheet("QPushButton{\n"
                                      "background-color: rgb(65,61,81);\n"
                                      "color: rgb(128,128,128);\n"
                                      "border: 2px solid rgb(55, 51, 71);\n"
                                      "border-radius: 8px;\n"
                                      "font:  italic 13pt \"Calibri\";\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover{\n"
                                      "    background-color: rgb(95, 91, 111);\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed{\n"
                                      "    background-color: rgb(128, 128, 128);\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "}")
        self.pushButton.setCheckable(False)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setGeometry(QtCore.QRect(720, 600, 101, 51))
        self.pushButton_2.setMouseTracking(False)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
                                        "background-color: rgb(65,61,81);\n"
                                        "color: rgb(128,128,128);\n"
                                        "border: 2px solid rgb(55, 51, 71);\n"
                                        "border-radius: 8px;\n"
                                        "font:  italic 13pt \"Calibri\";\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover{\n"
                                        "    background-color: rgb(95, 91, 111);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed{\n"
                                        "    background-color: rgb(128, 128, 128);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(720, 520, 101, 51))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
                                        "background-color: rgb(65,61,81);\n"
                                        "color: rgb(128,128,128);\n"
                                        "border: 2px solid rgb(55, 51, 71);\n"
                                        "border-radius: 8px;\n"
                                        "font:  italic 13pt \"Calibri\";\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover{\n"
                                        "    background-color: rgb(95, 91, 111);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed{\n"
                                        "    background-color: rgb(128, 128, 128);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(580, 600, 101, 51))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
                                        "background-color: rgb(65,61,81);\n"
                                        "color: rgb(128,128,128);\n"
                                        "border: 2px solid rgb(55, 51, 71);\n"
                                        "border-radius: 8px;\n"
                                        "font:  italic 13pt \"Calibri\";\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover{\n"
                                        "    background-color: rgb(95, 91, 111);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed{\n"
                                        "    background-color: rgb(128, 128, 128);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(580, 470, 101, 31))
        self.checkBox.setStyleSheet("color: rgb(128,128,128);\n"
                                    "\n"
                                    "font:  italic 10pt \"Calibri\";\n"
                                    "")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(730, 470, 101, 31))
        self.checkBox_2.setStyleSheet("color: rgb(128,128,128);\n"
                                      "\n"
                                      "font:  italic 10pt \"Calibri\";\n"
                                      "")
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalSlider_1 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_1.setMinimum(-80)
        self.horizontalSlider_1.setMaximum(0)
        self.horizontalSlider_1.setValue(0)
        self.horizontalSlider_1.setGeometry(QtCore.QRect(130, 120, 241, 51))
        self.horizontalSlider_1.setStyleSheet("QSlider::handle:horizontal {\n"
                                              "width: 18px;\n"
                                              "background-color: rgb(0, 0, 0);\n"
                                              "border-radius: 9px;\n"
                                              "\n"
                                              " \n"
                                              "}\n"
                                              "QSlider::groove:horizontal {\n"
                                              "border: 1px solid #999999;\n"
                                              "height: 18px;\n"
                                              "\n"
                                              "\n"
                                              "border-radius: 9px;\n"
                                              "}\n"
                                              " \n"
                                              "\n"
                                              "QSlider::add-page:qlineargradient {\n"
                                              "background: rgb(255,255,255);\n"
                                              "border-top-right-radius: 9px;\n"
                                              "border-bottom-right-radius: 9px;\n"
                                              "border-top-left-radius: 0px;\n"
                                              "border-bottom-left-radius: 0px;\n"
                                              "}\n"
                                              "\n"
                                              "QSlider::sub-page:qlineargradient {\n"
                                              "background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
                                              "border-top-right-radius: 0px;\n"
                                              "border-bottom-right-radius: 0px;\n"
                                              "border-top-left-radius: 9px;\n"
                                              "border-bottom-left-radius: 9px;\n"
                                              "}")
        self.horizontalSlider_1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_1.setObjectName("horizontalSlider_1")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setMinimum(-80)
        self.horizontalSlider_2.setMaximum(0)
        self.horizontalSlider_2.setValue(0)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(130, 190, 241, 51))
        self.horizontalSlider_2.setStyleSheet("QSlider::handle:horizontal {\n"
                                              "width: 18px;\n"
                                              "background-color: rgb(0, 0, 0);\n"
                                              "border-radius: 9px;\n"
                                              "\n"
                                              " \n"
                                              "}\n"
                                              "QSlider::groove:horizontal {\n"
                                              "border: 1px solid #999999;\n"
                                              "height: 18px;\n"
                                              "\n"
                                              "\n"
                                              "border-radius: 9px;\n"
                                              "}\n"
                                              " \n"
                                              "\n"
                                              "QSlider::add-page:qlineargradient {\n"
                                              "background: rgb(255,255,255);\n"
                                              "border-top-right-radius: 9px;\n"
                                              "border-bottom-right-radius: 9px;\n"
                                              "border-top-left-radius: 0px;\n"
                                              "border-bottom-left-radius: 0px;\n"
                                              "}\n"
                                              "\n"
                                              "QSlider::sub-page:qlineargradient {\n"
                                              "background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
                                              "border-top-right-radius: 0px;\n"
                                              "border-bottom-right-radius: 0px;\n"
                                              "border-top-left-radius: 9px;\n"
                                              "border-bottom-left-radius: 9px;\n"
                                              "}")
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_3.setMinimum(-80)
        self.horizontalSlider_3.setMaximum(0)
        self.horizontalSlider_3.setValue(0)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(130, 260, 241, 51))
        self.horizontalSlider_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalSlider_3.setStyleSheet("QSlider::handle:horizontal {\n"
                                              "width: 18px;\n"
                                              "background-color: rgb(0, 0, 0);\n"
                                              "border-radius: 9px;\n"
                                              "\n"
                                              "\n"
                                              " \n"
                                              "}\n"
                                              "QSlider::groove:horizontal {\n"
                                              "border: 1px solid #999999;\n"
                                              "height: 18px;\n"
                                              "\n"
                                              "\n"
                                              "border-radius: 9px;\n"
                                              "}\n"
                                              " \n"
                                              "\n"
                                              "QSlider::add-page:qlineargradient {\n"
                                              "background: rgb(255,255,255);\n"
                                              "border-top-right-radius: 9px;\n"
                                              "border-bottom-right-radius: 9px;\n"
                                              "border-top-left-radius: 0px;\n"
                                              "border-bottom-left-radius: 0px;\n"
                                              "}\n"
                                              "\n"
                                              "QSlider::sub-page:qlineargradient {\n"
                                              "background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
                                              "border-top-right-radius: 0px;\n"
                                              "border-bottom-right-radius: 0px;\n"
                                              "border-top-left-radius: 9px;\n"
                                              "border-bottom-left-radius: 9px;\n"
                                              "}")
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalSlider_4 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_4.setMinimum(-80)
        self.horizontalSlider_4.setMaximum(0)
        self.horizontalSlider_4.setValue(0)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(130, 330, 241, 51))
        self.horizontalSlider_4.setStyleSheet("QSlider::handle:horizontal {\n"
                                              "width: 18px;\n"
                                              "background-color: rgb(0, 0, 0);\n"
                                              "border-radius: 9px;\n"
                                              "\n"
                                              "\n"
                                              " \n"
                                              "}\n"
                                              "QSlider::groove:horizontal {\n"
                                              "border: 1px solid #999999;\n"
                                              "height: 18px;\n"
                                              "\n"
                                              "\n"
                                              "border-radius: 9px;\n"
                                              "}\n"
                                              " \n"
                                              "\n"
                                              "QSlider::add-page:qlineargradient {\n"
                                              "background: rgb(255,255,255);\n"
                                              "border-top-right-radius: 9px;\n"
                                              "border-bottom-right-radius: 9px;\n"
                                              "border-top-left-radius: 0px;\n"
                                              "border-bottom-left-radius: 0px;\n"
                                              "}\n"
                                              "\n"
                                              "QSlider::sub-page:qlineargradient {\n"
                                              "background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
                                              "border-top-right-radius: 0px;\n"
                                              "border-bottom-right-radius: 0px;\n"
                                              "border-top-left-radius: 9px;\n"
                                              "border-bottom-left-radius: 9px;\n"
                                              "}")
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.horizontalSlider_5 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_5.setMinimum(-80)
        self.horizontalSlider_5.setMaximum(0)
        self.horizontalSlider_5.setValue(0)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(130, 400, 241, 51))
        self.horizontalSlider_5.setStyleSheet("QSlider::handle:horizontal {\n"
                                              "width: 18px;\n"
                                              "background-color: rgb(0, 0, 0);\n"
                                              "border-radius: 9px;\n"
                                              "\n"
                                              "\n"
                                              " \n"
                                              "}\n"
                                              "QSlider::groove:horizontal {\n"
                                              "border: 1px solid #999999;\n"
                                              "height: 18px;\n"
                                              "\n"
                                              "\n"
                                              "border-radius: 9px;\n"
                                              "}\n"
                                              " \n"
                                              "\n"
                                              "QSlider::add-page:qlineargradient {\n"
                                              "background: rgb(255,255,255);\n"
                                              "border-top-right-radius: 9px;\n"
                                              "border-bottom-right-radius: 9px;\n"
                                              "border-top-left-radius: 0px;\n"
                                              "border-bottom-left-radius: 0px;\n"
                                              "}\n"
                                              "\n"
                                              "QSlider::sub-page:qlineargradient {\n"
                                              "background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
                                              "border-top-right-radius: 0px;\n"
                                              "border-bottom-right-radius: 0px;\n"
                                              "border-top-left-radius: 9px;\n"
                                              "border-bottom-left-radius: 9px;\n"
                                              "}")
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.horizontalSlider_6 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_6.setMinimum(-80)
        self.horizontalSlider_6.setMaximum(0)
        self.horizontalSlider_6.setValue(0)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(130, 470, 241, 51))
        self.horizontalSlider_6.setStyleSheet("QSlider::handle:horizontal {\n"
                                              "width: 18px;\n"
                                              "background-color: rgb(0, 0, 0);\n"
                                              "border-radius: 9px;\n"
                                              "\n"
                                              "\n"
                                              " \n"
                                              "}\n"
                                              "QSlider::groove:horizontal {\n"
                                              "border: 1px solid #999999;\n"
                                              "height: 18px;\n"
                                              "\n"
                                              "\n"
                                              "border-radius: 9px;\n"
                                              "}\n"
                                              " \n"
                                              "\n"
                                              "QSlider::add-page:qlineargradient {\n"
                                              "background: rgb(255,255,255);\n"
                                              "border-top-right-radius: 9px;\n"
                                              "border-bottom-right-radius: 9px;\n"
                                              "border-top-left-radius: 0px;\n"
                                              "border-bottom-left-radius: 0px;\n"
                                              "}\n"
                                              "\n"
                                              "QSlider::sub-page:qlineargradient {\n"
                                              "background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
                                              "border-top-right-radius: 0px;\n"
                                              "border-bottom-right-radius: 0px;\n"
                                              "border-top-left-radius: 9px;\n"
                                              "border-bottom-left-radius: 9px;\n"
                                              "}")
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.horizontalSlider_7 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_7.setMinimum(-80)
        self.horizontalSlider_7.setMaximum(0)
        self.horizontalSlider_7.setValue(0)
        self.horizontalSlider_7.setGeometry(QtCore.QRect(130, 540, 241, 51))
        self.horizontalSlider_7.setStyleSheet("QSlider::handle:horizontal {\n"
                                              "width: 18px;\n"
                                              "background-color: rgb(0, 0, 0);\n"
                                              "border-radius: 9px;\n"
                                              "\n"
                                              "\n"
                                              " \n"
                                              "}\n"
                                              "QSlider::groove:horizontal {\n"
                                              "border: 1px solid #999999;\n"
                                              "height: 18px;\n"
                                              "\n"
                                              "\n"
                                              "border-radius: 9px;\n"
                                              "}\n"
                                              " \n"
                                              "\n"
                                              "QSlider::add-page:qlineargradient {\n"
                                              "background: rgb(255,255,255);\n"
                                              "border-top-right-radius: 9px;\n"
                                              "border-bottom-right-radius: 9px;\n"
                                              "border-top-left-radius: 0px;\n"
                                              "border-bottom-left-radius: 0px;\n"
                                              "}\n"
                                              "\n"
                                              "QSlider::sub-page:qlineargradient {\n"
                                              "background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
                                              "border-top-right-radius: 0px;\n"
                                              "border-bottom-right-radius: 0px;\n"
                                              "border-top-left-radius: 9px;\n"
                                              "border-bottom-left-radius: 9px;\n"
                                              "}")
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setObjectName("horizontalSlider_7")
        self.horizontalSlider_8 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_8.setGeometry(QtCore.QRect(130, 610, 241, 51))
        self.horizontalSlider_8.setMinimum(-80)
        self.horizontalSlider_8.setMaximum(0)
        self.horizontalSlider_8.setValue(0)
        self.horizontalSlider_8.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.horizontalSlider_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalSlider_8.setAutoFillBackground(False)
        self.horizontalSlider_8.setStyleSheet("QSlider::handle:horisontal {\n"
                                              "width: 18px;\n"
                                              "background-color: rgb(0, 0, 0);\n"
                                              "border-radius: 9px;\n"
                                              "\n"
                                              " \n"
                                              "}\n"
                                              "QSlider::groove:horizontal {\n"
                                              "border: 1px solid #999999;\n"
                                              "height: 18px;\n"
                                              "\n"
                                              "\n"
                                              "border-radius: 9px;\n"
                                              "}\n"
                                              " \n"
                                              "\n"
                                              "QSlider::add-page:qlineargradient {\n"
                                              "background: rgb(255,255,255);\n"
                                              "border-top-right-radius: 9px;\n"
                                              "border-bottom-right-radius: 9px;\n"
                                              "border-top-left-radius: 0px;\n"
                                              "border-bottom-left-radius: 0px;\n"
                                              "}\n"
                                              "\n"
                                              "QSlider::sub-page:qlineargradient {\n"
                                              "background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
                                              "border-top-right-radius: 0px;\n"
                                              "border-bottom-right-radius: 0px;\n"
                                              "border-top-left-radius: 9px;\n"
                                              "border-bottom-left-radius: 9px;\n"
                                              "}")
        self.horizontalSlider_8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_8.setObjectName("horizontalSlider_8")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(450, 210, 501, 231))
        self.listWidget.setStyleSheet("background-color: rgb(54,54,66);\n"
                                      "color: rgb(128, 128, 128);\n"
                                      "border-radius: 20px;\n"
                                      "\n"
                                      "font:11pt \"Calibri\";\n"
                                      "")
        self.listWidget.setObjectName("listWidget")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(850, 150, 101, 51))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
                                        "background-color: rgb(65,61,81);\n"
                                        "color: rgb(128,128,128);\n"
                                        "border: 2px solid rgb(55, 51, 71);\n"
                                        "border-radius: 8px;\n"
                                        "font:  italic 13pt \"Calibri\";\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover{\n"
                                        "    background-color: rgb(95, 91, 111);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed{\n"
                                        "    background-color: rgb(128, 128, 128);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(460, 150, 101, 51))
        self.pushButton_6.setMouseTracking(False)
        self.pushButton_6.setTabletTracking(False)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
                                        "background-color: rgb(65,61,81);\n"
                                        "color: rgb(128,128,128);\n"
                                        "border: 2px solid rgb(55, 51, 71);\n"
                                        "border-radius: 8px;\n"
                                        "font:  italic 13pt \"Calibri\";\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover{\n"
                                        "    background-color: rgb(95, 91, 111);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed{\n"
                                        "    background-color: rgb(128, 128, 128);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "}")
        self.pushButton_6.setCheckable(False)
        self.pushButton_6.setAutoDefault(False)
        self.pushButton_6.setDefault(False)
        self.pushButton_6.setFlat(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(150, 20, 721, 71))
        self.textBrowser.setStyleSheet("background-color: #22222e;\n"
                                       "color: rgb(128,128,128);\n"
                                       "border: 2px solid #22222e;\n"
                                       "border-radius: 8px;\n"
                                       "font:  italic 28pt \"Calibri\";\n"
                                       "")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(380, 130, 61, 61))
        self.textBrowser_2.setStyleSheet("background-color: #22222e;\n"
                                         "color: rgb(128,128,128);\n"
                                         "border: 2px solid #22222e;\n"
                                         "border-radius: 8px;\n"
                                         "font:  italic 8pt \"Calibri\";")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(380, 200, 61, 61))
        self.textBrowser_3.setStyleSheet("background-color: #22222e;\n"
                                         "color: rgb(128,128,128);\n"
                                         "border: 2px solid #22222e;\n"
                                         "border-radius: 8px;\n"
                                         "font:  italic 8pt \"Calibri\";")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(380, 270, 61, 61))
        self.textBrowser_4.setStyleSheet("background-color: #22222e;\n"
                                         "color: rgb(128,128,128);\n"
                                         "border: 2px solid #22222e;\n"
                                         "border-radius: 8px;\n"
                                         "font:  italic 8pt \"Calibri\";")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(380, 340, 61, 61))
        self.textBrowser_5.setStyleSheet("background-color: #22222e;\n"
                                         "color: rgb(128,128,128);\n"
                                         "border: 2px solid #22222e;\n"
                                         "border-radius: 8px;\n"
                                         "font:  italic 8pt \"Calibri\";")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_6.setGeometry(QtCore.QRect(380, 410, 61, 61))
        self.textBrowser_6.setStyleSheet("background-color: #22222e;\n"
                                         "color: rgb(128,128,128);\n"
                                         "border: 2px solid #22222e;\n"
                                         "border-radius: 8px;\n"
                                         "font:  italic 8pt \"Calibri\";")
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_7.setGeometry(QtCore.QRect(380, 480, 61, 61))
        self.textBrowser_7.setStyleSheet("background-color: #22222e;\n"
                                         "color: rgb(128,128,128);\n"
                                         "border: 2px solid #22222e;\n"
                                         "border-radius: 8px;\n"
                                         "font:  italic 8pt \"Calibri\";")
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_8.setGeometry(QtCore.QRect(380, 550, 61, 61))
        self.textBrowser_8.setStyleSheet("background-color: #22222e;\n"
                                         "color: rgb(128,128,128);\n"
                                         "border: 2px solid #22222e;\n"
                                         "border-radius: 8px;\n"
                                         "font:  italic 8pt \"Calibri\";")
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_9.setGeometry(QtCore.QRect(380, 620, 61, 61))
        self.textBrowser_9.setStyleSheet("background-color: #22222e;\n"
                                         "color: rgb(128,128,128);\n"
                                         "border: 2px solid #22222e;\n"
                                         "border-radius: 8px;\n"
                                         "font:  italic 8pt \"Calibri\";")
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.textBrowser_10 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_10.setGeometry(QtCore.QRect(10, 130, 111, 31))
        self.textBrowser_10.setStyleSheet("background-color: #22222e;\n"
                                          "color: rgb(128,128,128);\n"
                                          "border: 2px solid #22222e;\n"
                                          "border-radius: 8px;\n"
                                          "font:  italic 8pt \"Calibri\";")
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.textBrowser_11 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_11.setGeometry(QtCore.QRect(10, 200, 111, 31))
        self.textBrowser_11.setStyleSheet("background-color: #22222e;\n"
                                          "color: rgb(128,128,128);\n"
                                          "border: 2px solid #22222e;\n"
                                          "border-radius: 8px;\n"
                                          "font:  italic 8pt \"Calibri\";")
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.textBrowser_12 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_12.setGeometry(QtCore.QRect(10, 270, 111, 31))
        self.textBrowser_12.setStyleSheet("background-color: #22222e;\n"
                                          "color: rgb(128,128,128);\n"
                                          "border: 2px solid #22222e;\n"
                                          "border-radius: 8px;\n"
                                          "font:  italic 8pt \"Calibri\";")
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.textBrowser_13 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_13.setGeometry(QtCore.QRect(10, 340, 111, 31))
        self.textBrowser_13.setStyleSheet("background-color: #22222e;\n"
                                          "color: rgb(128,128,128);\n"
                                          "border: 2px solid #22222e;\n"
                                          "border-radius: 8px;\n"
                                          "font:  italic 8pt \"Calibri\";")
        self.textBrowser_13.setObjectName("textBrowser_13")
        self.textBrowser_14 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_14.setGeometry(QtCore.QRect(10, 410, 111, 31))
        self.textBrowser_14.setStyleSheet("background-color: #22222e;\n"
                                          "color: rgb(128,128,128);\n"
                                          "border: 2px solid #22222e;\n"
                                          "border-radius: 8px;\n"
                                          "font:  italic 8pt \"Calibri\";")
        self.textBrowser_14.setObjectName("textBrowser_14")
        self.textBrowser_15 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_15.setGeometry(QtCore.QRect(10, 480, 111, 31))
        self.textBrowser_15.setStyleSheet("background-color: #22222e;\n"
                                          "color: rgb(128,128,128);\n"
                                          "border: 2px solid #22222e;\n"
                                          "border-radius: 8px;\n"
                                          "font:  italic 8pt \"Calibri\";")
        self.textBrowser_15.setObjectName("textBrowser_15")
        self.textBrowser_16 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_16.setGeometry(QtCore.QRect(10, 550, 111, 31))
        self.textBrowser_16.setStyleSheet("background-color: #22222e;\n"
                                          "color: rgb(128,128,128);\n"
                                          "border: 2px solid #22222e;\n"
                                          "border-radius: 8px;\n"
                                          "font:  italic 8pt \"Calibri\";")
        self.textBrowser_16.setObjectName("textBrowser_16")
        self.textBrowser_17 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_17.setGeometry(QtCore.QRect(10, 620, 111, 31))
        self.textBrowser_17.setStyleSheet("background-color: #22222e;\n"
                                          "color: rgb(128,128,128);\n"
                                          "border: 2px solid #22222e;\n"
                                          "border-radius: 8px;\n"
                                          "font:  italic 8pt \"Calibri\";")
        self.textBrowser_17.setObjectName("textBrowser_17")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.pushButton_2.setText(_translate("MainWindow", "Pause"))
        self.pushButton_3.setText(_translate("MainWindow", "Stop"))
        self.pushButton_4.setText(_translate("MainWindow", "Contiue"))
        self.checkBox.setText(_translate("MainWindow", "Overdrive"))
        self.checkBox_2.setText(_translate("MainWindow", "Delay"))
        self.pushButton_5.setText(_translate("MainWindow", "Load"))
        self.pushButton_6.setText(_translate("MainWindow", "IIR Filter"))
        self.textBrowser.setHtml(_translate("MainWindow",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'Calibri\'; font-size:28pt; font-weight:400; font-style:italic;\">\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; color:#808080;\">FIR FILTER</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'Calibri\'; font-size:8pt; font-weight:400; font-style:italic;\">\n"
                                              "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">0 dB</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("MainWindow",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'Calibri\'; font-size:8pt; font-weight:400; font-style:italic;\">\n"
                                              "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">0 dB</span></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("MainWindow",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'Calibri\'; font-size:8pt; font-weight:400; font-style:italic;\">\n"
                                              "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">0 dB</span></p></body></html>"))
        self.textBrowser_5.setHtml(_translate("MainWindow",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'Calibri\'; font-size:8pt; font-weight:400; font-style:italic;\">\n"
                                              "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">0 dB</span></p></body></html>"))
        self.textBrowser_6.setHtml(_translate("MainWindow",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'Calibri\'; font-size:8pt; font-weight:400; font-style:italic;\">\n"
                                              "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">0 dB</span></p></body></html>"))
        self.textBrowser_7.setHtml(_translate("MainWindow",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'Calibri\'; font-size:8pt; font-weight:400; font-style:italic;\">\n"
                                              "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">0 dB</span></p></body></html>"))
        self.textBrowser_8.setHtml(_translate("MainWindow",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'Calibri\'; font-size:8pt; font-weight:400; font-style:italic;\">\n"
                                              "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">0 dB</span></p></body></html>"))
        self.textBrowser_9.setHtml(_translate("MainWindow",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'Calibri\'; font-size:8pt; font-weight:400; font-style:italic;\">\n"
                                              "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">0 dB</span></p></body></html>"))
        self.textBrowser_10.setHtml(_translate("MainWindow",
                                               "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                               "p, li { white-space: pre-wrap; }\n"
                                               "</style></head><body style=\" font-family:\'Calibri\'; font-size:8pt; font-weight:400; font-style:italic;\">\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-style:normal;\">0 - 100 Hz</span></p></body></html>"))
        self.textBrowser_11.setHtml(_translate("MainWindow",
                                               "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                               "p, li { white-space: pre-wrap; }\n"
                                               "</style></head><body style=\" font-family:\'Calibri\'; font-size:8pt; font-weight:400; font-style:italic;\">\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-style:normal;\">101 - 258 Hz</span></p></body></html>"))
        self.textBrowser_12.setHtml(_translate("MainWindow",
                                               "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                               "p, li { white-space: pre-wrap; }\n"
                                               "</style></head><body style=\" font-family:\'Calibri\'; font-size:8pt; font-weight:400; font-style:italic;\">\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-style:normal;\">259 - 573 Hz</span></p></body></html>"))
        self.textBrowser_13.setHtml(_translate("MainWindow",
                                               "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                               "p, li { white-space: pre-wrap; }\n"
                                               "</style></head><body style=\" font-family:\'Calibri\'; font-size:8pt; font-weight:400; font-style:italic;\">\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-style:normal;\">574 - 1202 Hz</span></p></body></html>"))
        self.textBrowser_14.setHtml(_translate("MainWindow",
                                               "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                               "p, li { white-space: pre-wrap; }\n"
                                               "</style></head><body style=\" font-family:\'Calibri\'; font-size:8pt; font-weight:400; font-style:italic;\">\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-style:normal;\">1203 - 2459 Hz</span></p></body></html>"))
        self.textBrowser_15.setHtml(_translate("MainWindow",
                                               "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                               "p, li { white-space: pre-wrap; }\n"
                                               "</style></head><body style=\" font-family:\'Calibri\'; font-size:8pt; font-weight:400; font-style:italic;\">\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-style:normal;\">2460 - 4972 Hz</span></p></body></html>"))
        self.textBrowser_16.setHtml(_translate("MainWindow",
                                               "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                               "p, li { white-space: pre-wrap; }\n"
                                               "</style></head><body style=\" font-family:\'Calibri\'; font-size:8pt; font-weight:400; font-style:italic;\">\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-style:normal;\">4972 - 9997 Hz</span></p></body></html>"))
        self.textBrowser_17.setHtml(_translate("MainWindow",
                                               "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                               "p, li { white-space: pre-wrap; }\n"
                                               "</style></head><body style=\" font-family:\'Calibri\'; font-size:8pt; font-weight:400; font-style:italic;\">\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-style:normal;\">9998 - 20000 Hz</span></p></body></html>"))
