/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
 * Generated on: 12-Apr-2023 11:14:55
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 21
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\matlab\extern\include\tmwtypes.h 
 */
const int BL = 21;
const real64_T B[21] = {
   0.007335460370538, 0.009404949554812,  0.01540675906013,  0.02475828750297,
    0.03654714972222,  0.04962059901257,  0.06269867827165,  0.07449996827714,
     0.0838675511977,  0.08988277924595,  0.09195563556864,  0.08988277924595,
     0.0838675511977,  0.07449996827714,  0.06269867827165,  0.04962059901257,
    0.03654714972222,  0.02475828750297,  0.01540675906013, 0.009404949554812,
   0.007335460370538
};
