/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
 * Generated on: 24-Apr-2023 01:17:17
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 10
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\matlab\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 21
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
     0.5491481562352,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
     0.5491481562352,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
     0.5006715476248,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
     0.5006715476248,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
     0.4121975553588,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
     0.4121975553588,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
     0.2820656692516,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
     0.2820656692516,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
     0.1289010862124,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
     0.1289010862124,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
     0.8912509381337,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.5115149452361,   0.9641321843372 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.977939377962,   0.9950661861003 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.6386017548949,   0.8949902972638 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.963278931651,   0.9834099304156 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.8868461925962,    0.831179826614 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.936518521874,   0.9649220875576 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.206544404316,   0.7870298576241 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.880009395199,    0.929704170462 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.519833923638,   0.7949938052164 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.754146861574,   0.8644101603646 
  },
  {
                   1,                 0,                 0 
  }
};
