/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
 * Generated on: 24-Apr-2023 00:53:10
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 10
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\matlab\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 21
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
     0.9949890480558,                 0,                 0 
  },
  {
                   1,                -2,                 1 
  },
  {
     0.9932266506749,                 0,                 0 
  },
  {
                   1,                -2,                 1 
  },
  {
     0.9909055680436,                 0,                 0 
  },
  {
                   1,                -2,                 1 
  },
  {
     0.9876021907038,                 0,                 0 
  },
  {
                   1,                -2,                 1 
  },
  {
     0.9825172184445,                 0,                 0 
  },
  {
                   1,                -2,                 1 
  },
  {
     0.9739476197756,                 0,                 0 
  },
  {
                   1,                -2,                 1 
  },
  {
      0.957702435062,                 0,                 0 
  },
  {
                   1,                -2,                 1 
  },
  {
       0.92127641559,                 0,                 0 
  },
  {
                   1,                -2,                 1 
  },
  {
     0.8163958015254,                 0,                 0 
  },
  {
                   1,                -2,                 1 
  },
  {
     0.4523595269264,                 0,                 0 
  },
  {
                   1,                -2,                 1 
  },
  {
     0.8912509381337,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.981420278249,   0.9985359139738 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.977476225873,   0.9954303768266 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.971895972665,   0.9917262995089 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.963613955675,     0.98679480714 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.950562744586,   0.9795061291919 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.928292842879,   0.9674976362232 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.885817874379,   0.9449918658694 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.790323555961,   0.8947821063987 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.515106899763,   0.7504763063384 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.5596181478755,   0.2498199598302 
  },
  {
                   1,                 0,                 0 
  }
};
