/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
 * Generated on: 18-Apr-2023 13:22:49
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 13
 * Denominator Length  : 13
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\matlab\extern\include\tmwtypes.h 
 */
const int NL = 13;
const real64_T NUM[13] = {
     0.4502935179786,   -5.403522215743,    29.71937218659,   -99.06457395529,
      222.8952913994,    -356.632466239,    416.0712106122,    -356.632466239,
      222.8952913994,   -99.06457395529,    29.71937218659,   -5.403522215743,
     0.4502935179786
};
const int DL = 13;
const real64_T DEN[13] = {
                   1,   -10.58541892704,    51.49202855266,   -152.2399124634,
       304.787632646,   -435.4742733258,    455.5668192171,   -351.8455931609,
      199.2824489514,   -80.81473950645,    22.30280178136,    -3.76674323665,
     0.2949494837672
};
