/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
 * Generated on: 11-Apr-2023 10:56:31
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\matlab\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
#define MWSPT_NSEC 11
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const real32_T NUM[MWSPT_NSEC][3] = {
  {
   0.004248350859,              0,              0 
  },
  {
                1,              2,              1 
  },
  {
   0.003457140643,              0,              0 
  },
  {
                1,              2,              1 
  },
  {
   0.002201999538,              0,              0 
  },
  {
                1,              2,              1 
  },
  {
  0.0009566804511,              0,              0 
  },
  {
                1,              2,              1 
  },
  {
  0.0001897683687,              0,              0 
  },
  {
                1,              2,              1 
  },
  {
     0.8912509084,              0,              0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const real32_T DEN[MWSPT_NSEC][3] = {
  {
                1,              0,              0 
  },
  {
                1,   -1.977172256,   0.9941655993 
  },
  {
                1,              0,              0 
  },
  {
                1,    -1.96931982,   0.9831484556 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.965035319,   0.9738433361 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.963284969,   0.9671116471 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.962821007,   0.9635800123 
  },
  {
                1,              0,              0 
  }
};
