/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
 * Generated on: 23-Apr-2023 23:43:08
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 3
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\matlab\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 7
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
   0.004203972230824,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
   0.002338259348586,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
  0.0005196477382525,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
     0.8912509381337,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.967081659752,   0.9838975486755 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.947180527325,   0.9565335647194 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.938907469645,   0.9409860605984 
  },
  {
                   1,                 0,                 0 
  }
};
