/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
 * Generated on: 11-Apr-2023 10:55:48
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 11
 * Denominator Length  : 11
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\matlab\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int NL = 11;
const real32_T NUM[11] = {
   5.23293609e-15,5.232936006e-14,2.354821253e-13,6.279523342e-13,1.098916531e-12,
  1.318699815e-12,1.098916531e-12,6.279523342e-13,2.354821253e-13,5.232936006e-14,
   5.23293609e-15
};
const int DL = 11;
const real32_T DEN[11] = {
                1,   -9.837633133,     43.5933876,   -114.5860901,    197.8499146,
      -234.479538,     193.166626,   -109.2249603,    40.56947327,   -8.938212395,
     0.8870157003
};
