/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
 * Generated on: 23-Apr-2023 23:43:37
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 7
 * Denominator Length  : 7
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\matlab\extern\include\tmwtypes.h 
 */
const int NL = 7;
const real64_T NUM[7] = {
  4.552621650532e-09,2.731572990319e-08,6.828932475797e-08,9.105243301063e-08,
  6.828932475797e-08,2.731572990319e-08,4.552621650532e-09
};
const int DL = 7;
const real64_T DEN[7] = {
                   1,   -5.853169656723,     14.3010724702,   -18.66951405756,
      13.73409227931,   -5.398071888307,   0.8855911800063
};
