/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
 * Generated on: 24-Apr-2023 01:09:22
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 10
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\matlab\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 21
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
   0.004269974869376,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
   0.004058319672505,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
   0.003662119462134,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
   0.003119985833037,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
   0.002484585261118,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
   0.001817612621855,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
   0.001183880454514,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
  0.0006450611370375,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
  0.0002536764722445,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
  4.793221527459e-05,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
     0.8912509381337,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.981457536624,   0.9985374361014 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.979420423187,   0.9956537018769 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.978233796097,   0.9928822739451 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.977809221982,   0.9902891653141 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.977998002424,   0.9879363434681 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.978609965197,   0.9858804156842 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.979435772352,   0.9841712941703 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.980270638481,   0.9828508830287 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    -1.98093715405,   0.9819518599389 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.981304915342,   0.9814966442028 
  },
  {
                   1,                 0,                 0 
  }
};
