/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
 * Generated on: 24-Apr-2023 00:30:59
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 10
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\matlab\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 21
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
  4.278812340655e-05,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
  4.071171657067e-05,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
  3.676879705585e-05,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
  3.134550460936e-05,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
  2.497265301877e-05,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
  1.827376867811e-05,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
  1.190410483765e-05,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
  6.486589444739e-06,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
  2.550957542103e-06,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
  4.820044653797e-07,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
     0.8912509381337,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.999682080879,   0.9998532333722 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.999400529521,   0.9995633763868 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.999137271428,   0.9992843466164 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.998897619811,   0.9990230018298 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    -1.99868587008,   0.9987857606922 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.998505351291,   0.9985784463653 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.998358528445,   0.9984061448641 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.998247135144,   0.9982730815013 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.998172314501,   0.9981825183314 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.998134747002,   0.9981366750203 
  },
  {
                   1,                 0,                 0 
  }
};
