/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
 * Generated on: 18-Apr-2023 13:03:36
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 9
 * Denominator Length  : 9
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\matlab\extern\include\tmwtypes.h 
 */
const int NL = 9;
const real64_T NUM[9] = {
  4.881666146993e-12,3.905332917595e-11,1.366866521158e-10,2.733733042316e-10,
  3.417166302895e-10,2.733733042316e-10,1.366866521158e-10,3.905332917595e-11,
  4.881666146993e-12
};
const int DL = 9;
const real64_T DEN[9] = {
                   1,   -7.845695970949,     26.9647617737,   -53.02438004838,
      65.25042372553,   -51.45373358569,    25.39065003642,   -7.168592749318,
     0.8865668200832
};
